sudo: required

services:
  - docker

before_install:
  - docker build -t jogendrajangid/pritunlvpn:$TRAVIS_BUILD_NUMBER .
  - docker login -u $user -p $passwd
  - docker push jogendrajangid/pritunlvpn:$TRAVIS_BUILD_NUMBER

notifications:
  email:
    - jogendra.jangid@gmail.com
